"""add user warning table

Revision ID: d1e8ae5ef6bc
Revises: 
Create Date: 2025-05-12 20:23:45.449062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e8ae5ef6bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_warning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_warning', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_warning_time')
        batch_op.drop_column('timeout_end')
        batch_op.drop_column('ban_end')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_warning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ban_end', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('timeout_end', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('last_warning_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('last_warning')

    # ### end Alembic commands ###
